---
title: "Calidad endoscopía 2019"
author: "Ale"
date: "6 de julio de 2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Para comenzar, cargo todas las librerías que voy a usar

```{r echo=TRUE, results='hide'}
library(tidyverse)
library(dplyr)
library(gapminder)
library(readxl)
library(RUMBA)
library(sf)
library(osmdata)
library(ggmap)
library(janitor)
```

## Cargo las bases de datos y creo una sola tabla con las columnas de Saavedra. 

```{r}
lh <- read_excel("C:/Users/Ale/Desktop/Calidad-endoscop-a-2019/Las Heras 2019.xlsx")
saavedra <- read_excel("C:/Users/Ale/Desktop/Calidad-endoscop-a-2019/Saavedra 2019.xlsx")

head(lh)
head(saavedra)

colnames(saavedra)

estudios_total <- bind_rows(saavedra, lh) %>%
        select(c("Edad", "Terapeutica", "Operador", "Conclusiones1", "Conclusiones2", "Conclusiones3", "TipEs", "FecEstudio", "Sexo", "BostonI", "BostonD", "BostonT", "BostonTotal", "Direccion")) %>%
         mutate_at(vars(which(sapply(., is.character))), str_to_upper) 

head(estudios_total)
str(estudios_total)
```
total <- total %>%
        Select(

## Agrego geolocalización

```{r}
geo <- USIG_geocode(c("AV GRAL LAS HERAS 2900","GALVAN 4105"))

total <- cbind(estudios_total, geo) %>%
                        rename(Sede = address_normalised) %>%
                        select(-Direccion)

head(total)
```

## Empiezo limpieza de tablas

```{r}
unique(total$Operador)
unique(total$Terapeutica)

```

```{r}

total_tidy <- total %>%
                mutate(Operador = case_when (Operador == "PERALTA" | Operador == "Angel Daniel Peralta MN 92.347" ~ "AP", 
                                     Operador == "Juan Lasa MN 119929" | Operador == "Juan Lasa MN 119.929" ~ "JL",
                                     Operador ==  "Dr. Gustavo Cernadas MN 137.352" | Operador == "Gustavo Cernadas M.N. 137.352" ~ "GC",
                                     Operador == "Rafael Moore MN 85.298" ~ "RM", 
                                     Operador == "Alejandro Rey MN 134.017" ~ "AR",
                                     Operador == "Ignacio Fanjul MN 126.170" ~ "NF",
                                     Operador == "Pablo Olivera Sendra MN 129.392" ~ "PO",
                                     Operador == "Dima Guillermo MN84344" ~ "GD",
                                     TRUE ~ Operador),
                        Terapeutica = case_when(str_detect(Terapeutica, regex("p(o|e)l(i|p)", ignore_case = TRUE)) ~ "POLIPECTOMÍA",
                                       str_detect(Terapeutica, regex("muco", ignore_case = TRUE)) ~ "MUCOSECTOMÍA",
                                       str_detect(Terapeutica, regex("arg(o|ó|ò)n|apc", ignore_case = TRUE)) ~ "COAGULACIÓN CON PLASMA ARGÓN",
                                       str_detect(Terapeutica, regex("band|ligadura", ignore_case = TRUE)) ~ "LIGADURA DE VÁRICES ESOFÁGICAS",
                                       str_detect(Terapeutica, regex("sangr|hemost|lesiones|clips|urgencia", ignore_case = TRUE)) ~ "HEMOSTASIA LESIÓN SANGRANTE",
                                       str_detect(Terapeutica, regex("extrañ", ignore_case = TRUE)) ~ "EXTRACCION CUERPO EXTRAÑO",
                                       str_detect(Terapeutica, regex("gastrost", ignore_case = TRUE)) &! str_detect(Terapeutica, regex("RECAMBIO", ignore_case = T))~ "GASTROSTOMIA ENDOSCÓPICA",
                                       str_detect(Terapeutica, regex("dil(at|ta)", ignore_case = TRUE)) &! str_detect(Terapeutica, regex("colon", ignore_case = T)) ~ "DILATACIÓN ESOFÁGICA",
                                       str_detect(Terapeutica, regex("stent", ignore_case = TRUE)) &! str_detect(Terapeutica, regex("colon", ignore_case = T)) ~ "COLOCACIÓN DE STENT ESOFÁGICO",
                                       str_detect(Terapeutica, regex("dila", ignore_case = TRUE)) &! str_detect(Terapeutica, regex("esof", ignore_case = T)) ~ "DILATACIÓN COLÓNICA",
                                       str_detect(Terapeutica, regex("108|SNG|sonda", ignore_case = TRUE)) ~ "COLOCACIÓN DE SONDA NASOGÁSTRICA",
                                       str_detect(Terapeutica, regex("RECAMBIO", ignore_case = TRUE)) ~ "RECAMBIO DE BOTON GÁSTRICO",
                                       str_detect(Terapeutica, regex("e(s|x)cl(e|a)ro", ignore_case = TRUE)) ~ "ESCLEROTERAPIA DE ANGIODISPLASIA",
                                       str_detect(Terapeutica, regex("bipo", ignore_case = TRUE)) ~ "TERMOCOAGULACIÓN BIPOLAR",
                                       str_detect(Terapeutica, regex("botox|toxina", ignore_case = TRUE)) ~ "APLICACIÓN DE TOXINA BOTULÍNICA",
                                       str_detect(Terapeutica, regex("c(a|á)psula", ignore_case = TRUE)) ~ "COLOCACIÓN DE ENDOCÁPSULA",
                                       
                                       TRUE ~ Terapeutica),
                       TipEs = if_else(TipEs == "O", "G", TipEs)) %>%
        subset(Terapeutica != "NO REALIZADO" | is.na(Terapeutica))
 


unique(total_tidy$Terapeutica)

limpieza <- total_tidy %>% filter (Terapeutica == "RECAMBIO DE BOTON GÁSTRICO")
limpieza

```

